GET http://127.0.0.1:8080/catalog

###

POST http://127.0.0.1:8080/catalog
Content-Type: application/json

{
  "title": "40 Sfumature di rgb",
  "genre": "STRANO",
  "pubblicationYear": 2024,
  "author": "Marco Santorini",
  "price": 73.90,
  "quantity": 1000
}

###

POST http://127.0.0.1:8080/catalog
Content-Type: application/json

{
  "title": "La Bella e il Ricco",
  "genre": "BIOGRAFICO",
  "pubblicationYear": 1450,
  "author": "Enrico De Vittorio",
  "price": 89.90,
  "quantity": 3500
}
###

POST http://127.0.0.1:8080/catalog
Content-Type: application/json

{
  "title": "Il Minercraft",
  "genre": "HORROR",
  "pubblicationYear": 1990,
  "author": "Aula dev 1",
  "price": 79.90,
  "quantity": 50000
}


###
GET http://127.0.0.1:8080/catalog/title/re
###
GET http://127.0.0.1:8080/catalog/genre/strano

###
GET http://127.0.0.1:8080/catalog/author/re




